vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set termguicolors")
vim.cmd("set relativenumber")
vim.cmd("set nu rnu")
vim.cmd("set clipboard+=unnamedplus")
-- vim.cmd([[nnoremap <Left> :echo "No left for you!"<CR>]])
-- vim.cmd([[vnoremap <Left> :<C-u>echo "No left for you!"<CR>]])
-- vim.cmd([[inoremap <Left> <C-o>:echo "No left for you!"<CR>]])
-- vim.cmd([[nnoremap <Right> :echo "No right for you!"<CR>]])
-- vim.cmd([[vnoremap <Right> :<C-u>echo "No right for you!"<CR>]])
-- vim.cmd([[inoremap <Right> <C-o>:echo "No right for you!"<CR>]])
-- vim.cmd([[nnoremap <Up> :echo "No up for you!"<CR>]])
-- vim.cmd([[vnoremap <Up> :<C-u>echo "No up for you!"<CR>]])
-- vim.cmd([[inoremap <Up> <C-o>:echo "No up for you!"<CR>]])
-- vim.cmd([[nnoremap <Down> :echo "No down for you!"<CR>]])
-- vim.cmd([[vnoremap <Down> :<C-u>echo "No down for you!"<CR>]])
-- vim.cmd([[inoremap <Down> <C-o>:echo "No down for you!"<CR>]])
