vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=2")
vim.cmd("set termguicolors")
vim.cmd("set relativenumber")
vim.cmd("set nu rnu")
vim.cmd("set clipboard+=unnamedplus")
